export const monthNames = [
	/*"Jan",
	"Feb",
	"Mar",
	"Apr",*/
	"May",
	"Jun",
	"Jul",
	"Aug",
	"Sep",
	"Oct",
	/*"Nov",
	"Dec",*/
];

export const data = [
	{
		year: "2011",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Panorama", with: "Wanderung" }],
			[],
			[],
			[],
			[],
		],
	},
	{
		year: "2012",
		months: [
			[],
			[],
			[],
			[],
			[{ name: "High Falls Creek", with: "Other" }],
			[],
			[
				{ name: "Elfin Lakes", with: "Other" },
				{ name: "Rainbow Mountain", with: "Other" },
			],
			[
				{ name: "Brandywine", with: "Other", completed: false },
				{ name: "Panorama", with: "Wanderung" },
			],
			[
				{ name: "Mount Rohr", with: "Other" },
				{ name: "Ptarmigan Ridge", with: "Other" },
			],
			[{ name: "Semaphore Lakes", with: "Wanderung" }],
			[],
			[],
		],
	},
	{
		year: "2013",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Brandywine", with: "Eric", completed: false }],
			[],
			[
				{ name: "Gargoyles", with: "Wanderung" },
				{ name: "Wedgemount", with: "Wanderung" },
			],
			[
				{ name: "Strachan", with: "Other" },
				{ name: "Unnecessary", with: "Wanderung" },
			],
			[],
			[],
		],
	},
	{
		year: "2014",
		months: [
			[],
			[],
			[{ name: "Elfin Lakes", with: "Wanderung" }],
			[],
			[],
			[],
			[],
			[{ name: "Seymour", with: "Other" }],
			[],
			[],
			[],
			[],
		],
	},
	{
		year: "2015",
		months: [
			[{ name: "Rainbow Lake", with: "Wanderung" }],
			[{ name: "Harvey", with: "Wanderung" }],
			[],
			[],
			[],
			[
				{ name: "Goat Mountain", with: "Wanderung" },
				{ name: "Sea to Sky", with: "Eric" },
				{ name: "Joffre Lakes", with: "Other" },
			],
			[{ name: "Helm Creek", with: "Eric" }],
			[{ name: "Brandywine", with: "Other" }],
			[
				{ name: "Brew Lake", with: "Eric" },
				{ name: "Yellow Aster Butte", with: "Other" },
			],
			[],
			[],
			[],
		],
	},
	{
		year: "2016",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Coliseum", with: "Eric" }],
			[
				{ name: "Heliotrope Ridge", with: "Eric" },
				{ name: "Iceberg Lake", with: "Wanderung" },
				{ name: "Mount Price", with: "Wanderung" },
			],
			[
				{ name: "Needle Peak", with: "Eric" },
				{ name: "Locomotive", with: "Eric" },
			],
			[],
			[],
			[],
		],
	},
	{
		year: "2017",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Skyline (Squamish)", with: "Eric" }],
			[],
			[],
			[],
		],
	},
	{
		year: "2018",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Harvey", with: "Wanderung" }],
			[],
			[],
		],
	},
	{
		year: "2019",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Hanes Valley", with: "Other" }],
			[
				{ name: "Coliseum", with: "Wanderung" },
				{ name: "Panorama", with: "Eric" },
			],
			[{ name: "Watersprite", with: "Eric" }],
			[],
			[],
			[],
		],
	},
	{
		year: "2020",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Hydraulic", with: "Eric" }],
			[
				{ name: "Tricouni East", with: "Eric" },
				{ name: "Opal Cone", with: "Eric" },
			],
			[],
			[],
			[],
			[],
		],
	},
	{
		year: "2021",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Skyline (Squamish)", with: "Eric" }],
			[],
			[],
			[],
			[],
		],
	},
	{
		year: "2022",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[
				{ name: "Flora Peak", with: "Eric" },
				{ name: "Seed Peak", with: "Eric" },
			],
			[],
			[],
			[],
		],
	},
	{
		year: "2023",
		months: [
			[],
			[],
			[],
			[],
			[],
			[{ name: "Zupjok/Llama/Alpaca", with: "BCMC" }],
			[{ name: "Flora Peak", with: "Eric" }],
			[{ name: "Brandywine", with: "BCMC", completed: false }],
			[{ name: "Vantage", with: "Wanderung" }],
			[],
			[],
			[],
		],
	},
	{
		year: "2024",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[
				{ name: "Brandywine", with: "Wanderung" },
				{ name: "Elfin Lakes", with: "Greta" },
				{ name: "Strachan", with: "Greta" },
			],
			[{ name: "Golden Ears", with: "Other", completed: false }],
			[],
			[],
			[],
		],
	},
	{
		year: "2025",
		months: [
			[],
			[],
			[],
			[],
			[],
			[],
			[{ name: "Burwell", with: "Wanderung" }],
			[
				{ name: "Seymour", with: "Greta" },
				{ name: "Harvey", with: "Wanderung" },
				{ name: "Whirlwind", with: "Other", completed: false },
			],
			[],
			[],
			[],
			[],
		],
	},
	{
		year: "2026",
		months: [
			[],
			[],
			[],
			[],
			[],
			[
				{ name: "Brew Hut", with: "Wanderung" },
				{ name: "Burwell", with: "BCMC", completed: false },
			],
			[{ name: "Goat Mountain", with: "Greta" }],
			[],
			[
				{ name: "Goat Ridge", with: "BCMC" },
				{ name: "Zupjok/Llama/Alpaca", with: "BCMC" },
				{ name: "Mount Rohr", with: "BCMC" },
			],
			[],
			[],
			[],
		],
	},
];
